sudo: required
language: python
services:
    - rabbitmq
python:
    - "3.6"
    - "3.5"
    - "3.4"
before_script:
    - sudo rabbitmqctl add_user monitor monitor
    - sudo rabbitmqctl set_user_tags monitor monitoring
    - sudo rabbitmqctl set_permissions -p / monitor "^monitor-.*" ".*" ".*"
install:
    - make build
    - pip install codecov
    - pip install flake8

script:
    - make test
    - coverage run -m unittest */tests/*.py
after_success:
    - codecov
