language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"

install:
    - make clean
    - make build
    - pip install codecov
    - pip install flake8

script:
    - make test
    - coverage run -m unittest */tests/*.py
after_success:
    - codecov
