language: python
dist: xenial
python:
    - "3.7"
    - "3.6"
sudo: required
services:
    - rabbitmq
before_script:
    - sudo rabbitmqctl add_user monitor monitor
    - sudo rabbitmqctl set_user_tags monitor monitoring
    - sudo rabbitmqctl set_permissions -p / monitor "^monitor-.*" ".*" ".*"
install:
    - make build
    - pip install codecov
    - pip install flake8
    - pip install -r test_requirements.txt
script:
    - make test
    - pytest -v app/tests/ --cov=app --cov-report html
after_success:
    - codecov
