sudo: required
language: python
env:
    - SEFT_FTP_PORT=21
    - SEFT_FTP_USER=''
    - SEFT_FTP_PASS=''

services:
    - rabbitmq
python:
    - "3.6"
    - "3.5"
    - "3.4"
before_script:
    - sudo rabbitmqctl add_user monitor monitor
    - sudo rabbitmqctl set_user_tags monitor monitoring
    - sudo rabbitmqctl set_permissions -p / monitor "^monitor-.*" ".*" ".*"
install:
    - make build
    - pip install codecov
    - pip install flake8
    - pip install -r test_requirements.txt

script:
    - make test
    - pytest -v app/tests/ --cov=app --cov-report html
after_success:
    - codecov
